language: python
python:
  - "3.8"

cache: pip

branches:
  only:
  - main
  - dev

install:
  - pip install ruamel.yaml setuptools_scm
  - python -m conda2pip
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - python setup.py -q install

script:
  - pytest -v --cov=./

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
