coverage:
  status:
    project:
      default:
        # Allow coverage to drop `threshold` percent in PRs to main/dev
        target: auto
        threshold: 5%
        base: auto
        branches:
          - main
          - dev
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: true
